config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root "public#index"

  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account

  resources :accounts, only: [:index]
  resources :posts, only: [:show, :new, :create]
  resources :likes do
    collection do
      post :like
      post :dislike
    end
  end
  resources :comments, only: [:create, :destroy]

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :likes
  has_many :followers
  
  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_presence_of :comment
  validates_presence_of :account_id
  validates_presence_of :post_id
  
  attr_accessor :return_to

  after_create :increase_post_comment_counter
  after_destroy :decrease_post_comment_counter

  private
  def increase_post_comment_counter
    Post.find(self.post_id).increment(:total_comments_count).save
  end
  def decrease_post_comment_counter
    Post.find(self.post_id).decrement(:total_comments_count).save
  end
end

app/models/follower.rb
class Follower < ApplicationRecord
  #belongs_to :account
  validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :account
  validates_uniqueness_of :post_id, scope: :account_id

  after_create :increase_post_like_counter
  after_destroy :decrease_post_like_counter

  private
  def increase_post_like_counter
    Post.find(self.post_id).increment(:total_likes_count).save
  end
  def decrease_post_like_counter
    Post.find(self.post_id).decrement(:total_likes_count).save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc}
  mount_uploader :image, ImageUploader
  before_create :set_active
  belongs_to :account

  has_many :likes
  has_many :comments
  
  scope :active,->{ where(:active => true) }

  def set_active
    self.active = true
  end

  def total_likes
    self.total_likes_count
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_account, only: [:show, :profile]

  def index
    # user dashboard post feed
    followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    followers_ids << current_account.id

    @posts = Post.includes(:account).where(account_id: followers_ids).active
    @comment = Comment.new
    
    following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    following_ids << current_account.id

    @follower_suggestions = Account.where.not(id: following_ids)
    
  end

  def profile
    @posts = @account.posts.active
  end

  def show
  end

  def follow_account
    follower_id = params[:follow_id]
    
    if Follower.create!(follower_id:  current_account.id, following_id: follower_id)    
      flash[:success] = "Now following user"
    else
      flash[:danger] = "Try again"
    end

    redirect_to dashboard_path
  end
  private

  def set_account
    @account = Account.find_by(username: params[:username])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username,
                                                              :first_name,
                                                              :last_name, 
                                                              :email, 
                                                              :password, 
                                                              :image, 
                                                              :image_cache,
                                                              :description, 
                                                              :website])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password, :image, :image_cache])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_account!

  def create
    @comment = Comment.new(comment_params)
    @comment.account_id = current_account.id if account_signed_in?

    if @comment.save
      return_url = params[:comment][:return_to].present? ? post_path(@comment.post.id) : dashboard_path
      redirect_to return_url, flash: { success: "Comment was created successfully!!"}
    else
      redirect_to dashboard_path, flash: { danger: "Comment was created fail !!"}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id, :return_url)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    @like = Like.new(post_id: params[:post_id], account_id: current_account.id)
    @post_id = params[:post_id]

    existing_like = Like.where(post_id: params[:post_id], account_id: current_account.id)
    if existing_like.any?
      existing_like.first.destroy
    else
      @like.save
    end

    render json: { likes_count: Post.find(params[:post_id]).total_likes_count }
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_params, only:[:show]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_account.posts.build(post_params)

    if @post.save!
      redirect_to dashboard_path, flash: { success: "Post was created successfully!!"}
    else
      redirect_to new_path, flash: { danger: "Post was created fail !!"}
    end
  end

  def show
    @comment = Comment.new
    @comments = Comment.includes(:account).where(post_id: @post.id)
  end

  private
  def set_params
    @post = Post.find(params[:id]) if params[:id].present?
  end

  def post_params
    params.require(:post).permit(:image,
                                :image_cache,
                                :description
                                )
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def index
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def profile_picture(account, width = 100)
    image_path = account.image.present? ? account.image.thumb.url : "default.png"
    image_tag(image_path, width: width, class: "img-circle")
  end

  def can_edit_profile?(profile_id)
    account_signed_in? && current_account.id == profile_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def liked_by_user?(post_id)
    Like.where(post_id: post_id, account_id: current_account.id).any?
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
  <div class="recommended-follower">
    <div class="row">
      <div class="col-sm-3 col-lg-2">
        <%= link_to profile_picture(account, 40), profile_path(account.username) %>
      </div>
      <div class="col-sm-9 col-lg-10">
        <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
          <%= hidden_field_tag :follow_id, account.id %>
          <%= submit_tag "Follow", class: "btn btn-info btn-sm" %>
        <% end %>
        <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
        <p class="text-muted"><%= account.created_at < 2.days.ago ? "New to Instagram" : "Follow by users" %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <% @posts.each do |post| %>
        <div class="insta-post">
          <div class="post-meta">
            <%= link_to image_tag(post.account.image.thumb.url, class:"img-circle"), profile_path(post.account.username) %>
            <%= link_to post.account.username, profile_path(post.account.username), class:"text-dark" %>
          </div>
          <%= image_tag post.image.url, class: "img img-fluid" %>
          
          <div class="post-details" data-controller="like">
            <div class="post-actions" >
              <i class="fa fa-heart like-<%= post.id %> fa-2x post-like icon <%= "active" if liked_by_user?(post.id)%>" data-id=<%= post.id %> data-target="like.likebtn" data-action="click->like#like_or_not"></i>
              <%= link_to post_path(post.id) do %>
                <i class="fa fa-comment  fa-2x post-comment icon"></i>
              <% end %>
            </div>
            <p data-target="like.like_count" id="post-<%= post.id %>-likes"><strong><%= post.total_likes %></strong><strong> likes</strong></p>
            <p><strong id="post-<%= post.id %>-comments"></strong><%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %></strong></p>
            <%= simple_format post.description %>
            <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>
            <%= render "posts/comments" , post: post, comments: Comment.includes(:account).where(post_id: post.id)%>
          </div>

          <div class="comment-box">
            <%= form_for @comment do |f| %>
              <%= f.hidden_field :post_id, value: post.id %>
              <div class="input-group">
                <%= f.text_field :comment, placeholder: "Add comment here ....", class: "form-control post-comment" %>
                <div class="input-group-append">
                  <%= f.submit "Post", class: "btn btn-success float-right" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-4">
      <div class="account-summary">
        <div class="account_group">
          <%= link_to image_tag(current_account.image.thumb.url, class:"img-circle"), profile_path(current_account.username) %>
          <div class="col-6">
            <strong><%= current_account.username %></strong>
            <p><%= current_account.full_name %></p>
          </div>
        </div>
      </div>
      <div class="follower-suggestions">
        <%= link_to "View all", "#", class:"float-right text-dark" %>
        <p class="text-muted">Suggestions for you</p>
        <%= render "accounts/follower_suggestions"%>
      </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
    <div class="row">
      <div class="col-4 account_img">
        <%= profile_picture(@account, 200) %>
      </div>
      <div class="col-8 text-left profile-container">
        <div class="row"> 
          <div class="col-6" >
            <%= link_to "edit account", edit_account_registration_path, class: "btn btn-muted btn-custom float-right" if can_edit_profile?(@account.id) %>
            <h2><%= @account.full_name %></h2>
          </div>
        </div>
        <div class="profile-stats-group row">
          <div class="col-4">
            <div class="profile-stats"><%= @account.posts.count %> posts</div>
          </div>
          <div class="col-4">
            <div class="profile-stats"><%= @account.total_followers %> followers</div>
          </div>
          <div class="col-4">
            <div class="profile-stats"><%= @account.total_following %> following</div>
          </div>
        </div>
        <p><%= @account.full_name %></p>
        <p><%= simple_format @account.description %></p>
        <p><%= link_to @account.website if @account.website.present? %></p>
      </div>
      <div class="row profile-posts">

          <% @posts.each do |post| %>
          <div class="col-4">
            <div class="insta-post post-square" style="background: url(<%= post.image.url %>) no-repeat center top" >
            <%= link_to post_path(post) do %>
              <div class="post-stats">
                <div class="inner">
                  <i class="fa fa-heart"></i><%= post.total_likes_count %>
                  <i class="fa fa-comment m-l-15"></i><%= post.total_comments_count %>
                </div>
              </div>
            <% end %>
            </div>
          </div>
          <% end %>

      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyIg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white static-top">
      <div class="container">
        <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">
          <i class="fab fa-instagram"></i> | IG
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarResonsive" data-controls="navbarResonsive">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResonsive">
          <ul class="navbar-nav ml-auto">
            <%= render "shared/flash" %>
            <% if account_signed_in? %>
              <%= render "shared/account_nav" %>
            <% else %>
              <%= render "shared/public_nav" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
  <div class="comment">
    <%= link_to profile_picture(comment.account, 20), profile_path(comment.account.username) %>
    <strong><%= link_to comment.account.username, profile_path(comment.account.username), class: "text-muted"%></strong>
    <%= comment.comment %>
    <p class="text-muted m-l-30"><%= time_ago_in_words comment.created_at %> ago</p>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <%= f.submit "Save Post", class: "btn btn-success" %>

<% end %>

app/views/posts/new.html.erb
<h1>New</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="container post-details">
  <div class="row">
    <div class="col-8">
      <div class="insta-post">
        <%= image_tag @post.image.url, class: "img img-fluid" if @post.image.present? %>
      </div>
    </div>
    <div class="col-4">
      <div class="post-meta">
        <%= link_to image_tag(@post.account.image.thumb.url, class:"img-circle"), profile_path(@post.account.username) %>
        <%= link_to @post.account.username, profile_path(@post.account.username), class:"text-dark" %>
      </div>
      <div class="post-details" data-controller="like">
        <%= simple_format @post.description %>
        <div class="comments-feed">
          <%= render "posts/comments" , post: @post, comments: Comment.includes(:account).where(post_id: post.id)%>
        </div>
        <div class="post-actions" data-controller="comment">
          <i class="fa fa-heart like-<%= @post.id %> fa-2x post-like icon <%= "active" if liked_by_user?(@post.id)%>" data-id=<%= @post.id %> data-target="like.likebtn" data-action="click->like#like_or_not"></i>
          <i class="fa fa-comment  fa-2x post-comment icon" id="post-comment" data-target="comment.icon" data-action="click->comment#focus"></i>
        </div>
        <p data-target="like.like_count" id="post-<%= @post.id %>-likes"><strong><%= @post.total_likes %></strong><strong> likes</strong></p>
        <p><strong id="post-<%= @post.id %>-comments"></strong><%= link_to @post.account.username, profile_path(@post.account.username), class: "text-dark" %></strong></p>
        <p class="text-muted"><%= time_ago_in_words @post.created_at %> ago</p>
      </div>
      <div class="comment-box">
        <%= form_for @comment do |f| %>
          <%= f.hidden_field :post_id, value: @post.id %>
          <%= f.hidden_field :return_to, value: "post" %>
          <div class="input-group">
            <%= f.text_field :comment, placeholder: "Add comment here ....", class: "form-control post-comment" %>
            <div class="input-group-append">
              <%= f.submit "Post", class: "btn btn-success float-right" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_account_nav.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to "Home", dashboard_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "New Post", new_post_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</ul>  


app/views/shared/_flash.html.erb
<%if alert %>
  <%= alert %>
<% end %> 

app/views/shared/_navbar.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>  


app/views/shared/_public_nav.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>  